global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'spark'
    static_configs:
      - targets: ['spark-master:8081', 'spark-worker:8081']
  - job_name: 'trino'
    static_configs:
      - targets: ['trino:8085']